### ISSUE TITLE
Rapport de Bug

### ISSUE THREAD

**Issue by uwajambo** [Chaps06TV/ProjetIndustriel#4]
**Description du bug**
[Une description claire du bug]

Ticket ID :  TickDate1
Priorité   : 1
Projet     :   Contrôle industriel
Product owner : Joey
Testeur : Jean
Date émission : 14 Mars 2019

Description du bogue :    Menu : Commande- Champ   date :        

Un utilisateur est capable   de rentrer une date antérieure à une date de test ( le 14 Mars 2019).  Normalement l’application devait générer un   message d'exception lui disant qu’il doit choisir une date postérieur/même date   qu’aujourd’hui.

Ticket ID :  TickDate1
Priorité   : 1
Projet     :   Contrôle industriel
Product owner : Joey
Testeur : Jean
Date émission : 14 Mars 2019
Description du bogue : 
Menu : Commande- Champ nom : 

Un utilisateur est capable de rentrer autant de caractère qu’il veut. L'application devait limiter la taille de la  chaine « nom » à une longueur raisonable.

**Pour le reproduire**
Étapes pour reproduire le bug:
1. Aller à '...'
2. Cliquer sur '....'
3. Erreur

**Ce qui devrait se produire**
[Une description claire de ce qui devrait se produire]

**Screenshots**
[Si applicable, inclure des screenshots]

**PC:**
 - OS: [e.g. Windows 10]
 - Fureteur [e.g. chrome, safari, firefox]

**Information additionnelle**
[Décrire toute information additionnelle]

**Comment by 2601637** [comment]
Bug Commande- Champ date:
Nous avons modifier le code pour empêcher l'utilisateur de sélectionné une date antérieure de la date présente(aujourd’hui). 

Bug Commande- Champ nom:
Nous avons modifier le code afin de limité le nombre de caractère a 50 pour le nom

**Comment by uwajambo** [comment]
Tiecket fermé avec succes.
Merci
